### ISSUE TITLE
Alternative for ArcGIS provider

### ISSUE THREAD

**Issue by wantell** [geocoder-php/Geocoder#1089]
Hello,

I work on a site which requires us to use ArcGIS and store the results. Per their terms of service, this requires an account with their service in order to provide a token, which the ArcGISOnline provider class/package does not support.

In order for us to be compliant, I have made a variation of ArcGISOnline called [ArcGISList](https://github.com/wantell/arcgis-geocode-addresses). This allows the use of the token in order to reach the geocodeAddresses endpoint instead of the find endpoint. I don't know if there is any demand for it but I would like to submit it for either incorporating into ArcGISOnline, or as an alternative.

Please let me know if you have any questions.

**Comment by jbelien** [comment]
Hello @wantell,

Since `/find` seems indeed deprecated for [`/findAddressCandidates`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find-address-candidates.htm) and our provider doesn't support [`/geocodeAddresses`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-geocode-addresses.htm), I would suggest to upgrade/extend our provide with a PR.

Here is what I would suggest:

- Migrate `/find` to `/findAddressCandidates`
- Add support for `token` parameter
- Replace `/findAddressCandidates` by `/geocodeAddresses` if there is a token (I didn't check if the response of `/findAddressCandidates` and `/geocodeAddresses` are the same)

Does that make sense ?
Would you be able to send a PR to upgrade our ArcGIS Online provider ?

Thanks!

**Comment by wantell** [comment]
Hi @jbelien,

I will work on creating the PR.

**Comment by wantell** [comment]
Hi @jbelien,

I have created the PR: https://github.com/geocoder-php/Geocoder/pull/1090

Please let me know if you have any questions. I don't know if you are involved with the Drupal module but I will be submitting a code update to them to integrate with this change.

**Comment by atymic** [comment]
Awesome job @wantell!
