### ISSUE TITLE
Chain provider should return provider name with results

### ISSUE THREAD

**Issue by stevevance** [geocoder-php/Geocoder#399]
When using a chain of geocoding providers, each Address and AddressCollection object should contain the name of the provider that created it.

**Comment by Baachi** [comment]
I don't think so, the `ChainProvider` should be invisible. And it should not matter which provider you use, the format of the result should be the same. 

The goal of this library is to provide an unified way to geocode data.

**Comment by willdurand** [comment]
> the ChainProvider should be invisible.

:+1:

**Comment by stevevance** [comment]
Different providers give different results for the same query. I realize I can build each provider separately (not in a chain) but it would be a convenience method (just like ````getLatitude()```` ) to tell me who's providing good or bad results (so I can drop the ones that are continually bad).

**Comment by stevevance** [comment]
Does the ChainProvider consider each provider's resulting confidence score?

**Comment by giosh94mhz** [comment]
@stevevance I'm now editing all provider code (for #398) and I'm pretty sure that providers don't check confidence score of returned values.

For now you may order the providers so that the best one comes before the others. If you are using `BazingaGeocoderBundle`, you can create your own specialization of `ChainProvider` and then override the property `bazinga_geocoder.geocoder.provider.chain.class` in your configuration.

@willdurand  @Baachi Maybe the score is something that should be integrated in the providers code. For example, while testing the `BingProvider` I found that high confidence result were good, but the medium confidence results were surprising.

**Comment by willdurand** [comment]
I think it should be another provider which would mimic the `Chain` one.

**Comment by toin0u** [comment]
I'm also for an other provider and I think the use case is valid.

**Comment by stevevance** [comment]
@giosh94mhz The problem with ordering the providers is that I don't know which provider has the best result for any given address. My application is geocoding 50-100 addresses per day. 

One thing that may help my application is normalizing the user's input to a common format that geocoders may have a better time dealing with. Do you know of any?

**Comment by giosh94mhz** [comment]
@stevevance The only thing I can think of, is a custom "ChainFilterProvider" (first random name that comes to mind), in which you get results from more than one Provider and then choose the best from them. Something like the movie "Minority Report": you get three result and exclude the one with the "random" result; in this case "random" can be defined as not geographically near the other two. Not so comfortable, I know. 

Anyway I really liked the idea of putting the score in; after I've finished with testing the provider in the other PR, I'll probably open a new PR ;)
