### ISSUE TITLE
Admin level constants

### ISSUE THREAD

**Issue by Bogdaan** [geocoder-php/Geocoder#428]
How about to create constant values for:
* city
* country
* locality

In **models/AdminLevel.php**:

    /**
     * @var int
     */
    private $level;

**Comment by willdurand** [comment]
tell me more about it

**Comment by Bogdaan** [comment]
I am use only google provider:
for "city" and "locality" ( 1 and 3 ).

But posible diffrent providers set diffrent admin level codes ( 1 - 5 level )

**Comment by giosh94mhz** [comment]
@Bogdaan I've implemented the admin level part of Geocoder in place of the previously defined county, region, ... so I think I can help you.

It is not possible to define which level will provide a region or a locality, as the same information can be provided at different level for different provider. The invariant is that level 5 is contained in level 4, ..., which is contained in level 1; nothing more.

In theory (and in all my tests), all providers properly fill admin level starting with one, and there are not holes (e.g. level 1 and 3 present, without level 2). If you define a constant for the locality, you should then guarantee that the constant apply to all providers which is not possible.

Also note that the locality is still provided as a separate method, and may just be duplicated as the last admin level. This is because, multiple "location" could be grouped in the same "political location".

What you can actually do, is to provide your custom provider with the macro you are suggesting. This way, you could wrap "google" and other provider and map admin level as you wish.

Hope this will help! ;)

**Comment by Bogdaan** [comment]
ok, thanks
