### ISSUE TITLE
Misleading exception NoResult

### ISSUE THREAD

**Issue by pavolsenko** [geocoder-php/Geocoder#508]
Exception `NoResult` is a bit confusing. For example in `GoogleMaps` provider it's thrown when there is no/incorrect response from the server (no JSON returned) but also when there is a response but with zero results. It's message is also confusing saying "Could not execute query". This is not true. Query has been excuted correctly and returned valid JSON but this JSON is saying `ZERO_RESULTS`. This should be two different exceptions: one for invalid response from server and one for valid response but with zero results (`ZeroResults` exception? :wink: ). I've briefly checked other providers and they have similar problem with this exception. 
Thanks.

**Comment by willdurand** [comment]
Yes, I do agree with you. Wanna contribute?

**Comment by pavolsenko** [comment]
Sure :)

**Comment by Nyholm** [comment]
Fixed by #572

**Comment by FinesseRus** [comment]
@willdurand This issue is fixed for version 4.x which is still not stable and not released. So we still face the problem on a stable 3.x version. May you or I fix it for 3.x version?

**Comment by Nyholm** [comment]
If this should be fixed for 3.x we need to consider BC. Or the invalid server response exception must extend zeroResultException. 
I currently focus all my efforts on finishing 4.0 before August, I do not have time to create such PR. But I would be happy to review a PR to the 3.x branch to fix this issue.

**Comment by FinesseRus** [comment]
@Nyholm I understand, I will workaround it somehow on my side.

I can't understand this:

```php
class InvalidServerResponse extends ZeroResults
```

Why is `InvalidServerResponse` a subtype of `ZeroResults`? I believe that `InvalidServerResponse` is a sign of a problem that need to be fixed by a developer or administrator, and `ZeroResults` is a normal runtime situation (given address doesn't exist). I wouldn't extend one by another or I would just return an empty address collection in case of zero results. Am I wrong? Maybe I don't understand something.

**Comment by Nyholm** [comment]
I agree with you. That is why it is changed in master: https://github.com/geocoder-php/Geocoder/blob/master/src/Common/Exception/InvalidServerResponse.php#L20

**Comment by FinesseRus** [comment]
@Nyholm Oh, sorry, I didn't see it. Thank you for the answer!
