### ISSUE TITLE
Admin Level Inconsistency

### ISSUE THREAD

**Issue by lupoair** [geocoder-php/Geocoder#511]
Reading former issues here, I understand how you derived at your current Admin Level system implemented. #392 #398 

And it all makes sense to a degree. It is clear that every country has different Admin Levels.

My issue takes place with locations within a certain country and their own Admin Level hierarchy and how to handle differences and inconsistencies. Let's take Germany for example since there has been a similar open discussion #483 . Here you can have cities with state, region and county but not necessarily. One city can have a region while the next one doesn't.

GeoNames therefore delivers empty admin_level_2 (Region) for those cities.

Look at "adminName2": ""

``` json
{"geonames": [{
  "adminCode3": "03458",
  "adminCode2": "00",
  "countryName": "Germany",
  "adminCode1": "06",
  "lng": "8.55947",
  "adminCode4": "03458005",
  "adminName2": "",
  "fcodeName": "populated place",
  "adminName3": "Landkreis Oldenburg",
  "distance": "0.82744",
  "timezone": {
    "dstOffset": 2,
    "gmtOffset": 1,
    "timeZoneId": "Europe/Berlin"
  },
  "adminName4": "Ganderkesee",
  "adminName5": "",
  "name": "Almsloh",
  "fcode": "PPL",
  "geonameId": 2958212,
  "asciiName": "Almsloh",
  "lat": "53.05641",
  "population": 0,
  "adminName1": "Lower Saxony",
  "adminId1": "2862926",
  "countryId": "2921044",
  "fclName": "city, village,...",
  "elevation": 0,
  "countryCode": "DE",
  "adminId4": "6552965",
  "adminId3": "2857455",
  "toponymName": "Almsloh",
  "fcl": "P",
  "continentCode": "EU"
}]}
```

This goes against previous comment @giosh94mhz #428 

> [...] In theory (and in all my tests), all providers properly fill Admin Level starting with one, and there are not holes (e.g. level 1 and 3 present, without level 2). [...]

Based on the above comment **GeoNames** implementation drops empty Admin Levels:

/src/Geocoder/Provider/Geonames.php#140

``` php
for ($level = 1; $level <= AdminLevelCollection::MAX_LEVEL_DEPTH; ++ $level) {
    $adminNameProp = 'adminName' . $level;
    $adminCodeProp = 'adminCode' . $level;
    if (! empty($item->$adminNameProp) || ! empty($item->$adminCodeProp)) {
        $adminLevels[] = [
            'name' => empty($item->$adminNameProp) ? null : $item->$adminNameProp ,
            'code' => empty($item->$adminCodeProp) ? null : $item->$adminCodeProp,
            'level' => $level,
        ];
    }
}
```

Which results in different Admin Level sets within the same country. Admin Level 2 may contain a region or maybe a county.

Another issue would take place when using **OpenStreetMap** as a provider. Here the Admin Level has been taken ad absurdum since for all countries only state and county are being imported.

/src/Geocoder/Provider/Nominatim.php#111

``` php
$adminLevels = [];
foreach (['state', 'county'] as $i => $tagName) {
    if (null !== ($adminLevel = $this->getNodeValue($addressNode->getElementsByTagName($tagName)))) {
        $adminLevels[] = ['name' => $adminLevel, 'level' => $i + 1];
    }
}
```

This way a lot of information is lost/unusable in most countries as you can see in the listing #392 .

How would I safely extract the county using GeoNames for Germany cities for example? Even though every city in German will have a county it will not always be at the same Admin Level.

**Comment by giosh94mhz** [comment]
Thanks for pinging me in.

> Based on the above comment GeoNames implementation drops empty Admin Levels

This is correct IMO. The admin model ovject is not created if there aren't useful informations. Note that you have to iterate the admin level using `AdminLevelCollection` which is an `IteratorAggregate` with admin level number has key. This is the best that comes to mind...

> Which results in different Admin Level sets within the same country.

And never look to China, which is a mess! :) There may  be holes (e.g. 1, 3 not 2), but within the same provider admin level are consistent.

> Another issue would take place when using OpenStreetMap as a provider. Here the Admin Level has been taken ad absurdum since for all countries only state and county are being imported.

You got a point here. The problem is that I have migrated the previous codebase and done my best in analyzing all the output from all providers. I probably missed something out by testing only few countries, but as I pointed out in https://github.com/geocoder-php/Geocoder/pull/398#issuecomment-69582032 handling OpenStreetMap admin level is hard.

> Even though every city in German will have a county it will not always be at the same Admin Level

That sounds like a bug (in OpenStreetMap?) which could be fixed. Please open a dedicated issue with a couple of api call which expose the issue and I can help in fixing this.

Also note that the library does it's best in having admin level filled as [1, 2, 3] without holes, but does not impose strict requirements on admin levels between providers. When you use multiple chain loaded provider you should do some testing and provide feedback if you spot anomalies.

Disclaimer: I'm not one of the maintainers, but hope is in line with them :)
