### ISSUE TITLE
egeloen/http-adapter dependency version ~0.8 to ~1.0

### ISSUE THREAD

**Issue by ollierattue** [geocoder-php/Geocoder#519]
v3.3.0 of willdurand/geocoder requires egeloen/http-adapter: ~0.8. Can this be increased to ~1.0?

An example of a conflict I'm seeing:

```
Your requirements could not be resolved to an installable set of packages.

- florianv/swap v2.6.0 requires egeloen/http-adapter ~1.0 -> satisfiable by egeloen/http-adapter[1.0.1, 1.0.0].

- willdurand/geocoder v3.3.0 requires egeloen/http-adapter ~0.8 -> satisfiable by egeloen/http-adapter[0.8.0].
```

**Comment by Nyholm** [comment]
There is an accepter PR to remove the dependency for `egeloen/http-adaper` completely. We are just waiting for a contributor to merge it. 

See https://github.com/geocoder-php/Geocoder/pull/512

Btw, There is also a PR on `florianv/swap` to remove `egeloen/http-adaper`. Im waiting for @florianv to make his final review. 

Im going to close this issue because of the existing PR. Feel free to continue the discussion.

**Comment by ollierattue** [comment]
Thanks for the info.
