### ISSUE TITLE
GoogleMaps::__construct() adapter instance

### ISSUE THREAD

**Issue by pedro380085** [geocoder-php/Geocoder#524]
When I run:

```
$adapter  = new \Http\Adapter\Guzzle6\Client();
$geocoder = new \Geocoder\Provider\GoogleMaps($adapter);
```

It gives me the following error:
`Argument 1 passed to Geocoder\Provider\GoogleMaps::__construct() must be an instance of Ivory\HttpAdapter\HttpAdapterInterface, instance of Http\Adapter\Guzzle6\Client given`

Someone has any idea of what may be wrong?

**Comment by Nyholm** [comment]
You are looking at the docs for the master branch but you have downloaded the latest stable release. 

We are soon about to tag 4.0 please give `dev-master` a try since you starting to use this geocoder. 

Alternatively (not recommended), see the docs for version 3.3.0: https://github.com/geocoder-php/Geocoder/tree/v3.3.0

**Comment by corysimmons** [comment]
Care to update master README so it actually works instead of assuming people have knowledge of branches and such that are in-the-works?

Also https://github.com/egeloen/ivory-http-adapter looks deprecated.

**Comment by Nyholm** [comment]
Im not too sure what you mean @corysimmons. The main issue here is that the readme actually **is updated**. It seams like you also downloaded the latest stable version, you should look at the readme for the files you downloaded. If you download `dev-master` the readme on the [repository startpage](https://github.com/geocoder-php/Geocoder) is up to date (and we do not use ivory anymore.

**Comment by nicoflemming** [comment]
I have the same problem.
>  (and we do not use ivory anymore.

But why tells my the adapter that parameter has to be an instance of Ivory\HttpAdapter\HttpAdapterInterface ??

I tried the example from for docs:

$adapter  = new \Http\Adapter\Guzzle6\Client();
$this->geocoder = new \Geocoder\Provider\GoogleMaps($adapter);

And it results in:

Type error: Argument 1 passed to Geocoder\Provider\GoogleMaps::__construct() must be an instance of Ivory\HttpAdapter\HttpAdapterInterface, instance of Http\Adapter\Guzzle6\Client given

By the way: Ivory\HttpAdapter\HttpAdapterInterface is DEPRECATED. So you do you want to use it?

**Comment by joekhartley** [comment]
@nicoflemming  I think I may have found a solution to this through looking over the dependencies and finding the **Guzzle6HttpAdapter** reference within the configuration file.

When I alter the example given in the documentation, it seems to work.

So Instead of this:

```
$adapter = new \Http\Adapter\Guzzle6\Client();
$this->geocoder = new \Geocoder\Provider\GoogleMaps($adapter);
```

I added `use Ivory\HttpAdapter\Guzzle6HttpAdapter;` top the includes and used the following:

```
$config = [];
$httpAdapter = new Guzzle6HttpAdapter(new GuzzleClient($config));
$geocoder = new \Geocoder\Provider\GoogleMaps($httpAdapter, 'Bukingham Palace, London', 'UK', true, config('app.google_maps_api_key'));
```


And when I dd($geocoder); it returned the appropriate instance of the GoogleMaps class I was using.
