### ISSUE TITLE
Our interfaces

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/Geocoder#574]
Currently we have the following interfaces for geocoder/providers: 

```php
interface LocaleAwareProvider extends Provider {
  public function getLocale();
  public function setLocale($locale);
}
interface Provider extends Geocoder {
  public function getName();
}
interface Geocoder {
  public function geocode($value);
  public function reverse($latitude, $longitude);
  public function getLimit();
  public function limit($limit);
}
```

Is there a reason why a Geocoder cannot have a name? If we should add support for a `Location::providedBy` (#490) I think all Geocoder should have a name. 

I would also like to hear voices about the interface inheritance. Must the `LocaleAwareProvider` really be a `Provider`?

I suggest the following: 

```php
interface LocaleAware {
  public function getLocale();
  public function setLocale($locale);
}

interface Geocoder {
  public function geocode($value);
  public function reverse($latitude, $longitude);
  public function getLimit();
  public function limit($limit);
  public function getName();
}
```

-------------

I suggest we start to add interfaces for features. In #501 I suggested to add a `BoundsAware`.
```php
interface BoundsAware {
  public function setBounds(Bounds $bounds);
}
```

I do also want an interface for providers that supports IP addresses. (Right now we have no way to tell)
```php
interface IpAddressGeocoder {
}
```

**Comment by Nyholm** [comment]
Any thoughts? @toin0u @Baachi?

**Comment by willdurand** [comment]
> Is there a reason why a Geocoder cannot have a name?

Yes. There is no need for it, but it requires more context to understand.

What's important is the distinction between providers and geocoders, which lies in the original goal of the lib: being able to switch providers ~~easily~~ without even noticing anything. That is why you always talk to a `Geocoder` (asking it a service like `geocode()`). Initially, a provider was returning data, letting the Geocoder figure out how to return the right information to the user. In order to ease things and allow many more scenarios, this logic moved from the `Geocoder` (at that time, there was only one single geocoder, and you had to pass it a `Provider`) to each `Provider`, making these providers smarter. Hence, the former `Geocoder` was renamed to "aggregator" (or something like this), because it was only useful to register the providers and deciding on the one to call. To keep BC, both this aggregator and the providers had to share a similar interface, the `Geocoder` interface. This new interface carries both the logic move and the intent of a uniform API. But a provider depends on a service, hence it needs to be named. That is why there is a `Provider` interface, which is basically `Geocoder` + `name`. All of this respects the Composite pattern IIRC 😃 

> Must the LocaleAwareProvider really be a Provider?

I would say yes because it is a feature of a provider. It cannot be separated in the context of Geocoder, because "locale" does not mean anything in the "geocoding word". Yet, a "locale aware service/geocoder/provider" does. That is why we cannot separate both IMO.

---

I do agree with the rest of your text: having interfaces for features is a huge :+1:, same for the `IpAddress` marker interface.

**Comment by Nyholm** [comment]
Thank you for a really good answer. It gave me some better context. 
Your arguments with LocaleAwareProvider makes sense. Thanks. 

No changes should be made to existing interfaces prior 4.0.

**Comment by Nyholm** [comment]
It is still something that does not **feel** right. It is probably something I do not understand. I really hate making arguments on feelings instead of good software design... 

As I understand, the only need for the provider::getName is for the ProviderAggregator. But one could refactor that class so the need for getName goes away. Maybe remove that function completely?

Since all providers are geocoders I think/feel like it is a good idea to reduce complexity and remove one interface. I think I have this opinion because I was not with you guys at the start and currently there are no real difference between a provider and a geocoder.

**Comment by unkind** [comment]
Why do you want to make different interfaces rather than, let's say, query object like 
```php
final GeocoderQuery
{
    public function withBounds(Bounds $bounds): GeocoderQuery;
    public function withLocale(Locale $locale): GeocoderQuery;
    // ...
}
```
?

As you can see in #576 it doesn't look convenient when you need to mix "features", and also these interfaces make providers stateful, this is a sign of problem.

**Comment by Nyholm** [comment]
A query object is a good idea. But it would change the way people are using the geocoders. I'm not too sure it would be apprichiated. 

Can you explain why there is a problem of making providers stateful?

**Comment by unkind** [comment]
> Can you explain why there is a problem of making providers stateful?

In case of PHP, it adds complexity and increases chance of bugs.

```php
$this->provider->setBounds(new Bounds(...));
// What if this service make similar request to the same geocoder with different bounds?
$this->foo->bar(); 
$this->provider->geocode(...); 
```

```php
final CustomProvider implements Provider, LocaleAware, BoundsAware
{
    use LocaleAwareTrait, BoundsAwareTrait;

    public function geocode($name)
    {
        // What if we change locale/bounds after first request?
        // It's easy to forget to drop the cache in setLocale/setBounds.
        if (isset($this->runtimeCache[$name])) {
            return $this->runtimeCache[$name];
        }

        // ...
    }
}
```

In more general cases, it also makes objects thread-unsafe.

I see two ways to avoid mutability/statefulness:
* inject bounds/locale through constructor and use factory to create providers;
* pass bounds/locale directly to the query method, i.e. make them part of the query object.

However, `bounds` doesn't look like a constructor parameter of provider at all, that's why I suggest to make a query object.

**Comment by unkind** [comment]
Real-life example when mutability introduced a bug: https://github.com/symfony/symfony/pull/21098

**Comment by Nyholm** [comment]
Thank you for the explanation and thank you for the link. 

> In case of PHP, it adds complexity and increases chance of bugs.

This is not a valid argument. Any added line of code adds complexity and increases changes for bugs =)

> In more general cases, it also makes objects thread-unsafe.

PHP is not using threads... 

> It's easy to forget to drop the cache in setLocale/setBounds.

Yes, that is why we have tests... (Also, you are doing cache wrong)

Let's stay relevant and focused on the current topic. 

----------

I like your idea of making providers immutable, but it has nothing to do with state. I also like your idea of a query object more and more...

What do you think is the best way to proceed? Considering making it easy for people migrating to 4.0? Can you give a example of how all the interfaces should look like, including the new features?

**Comment by unkind** [comment]
> I like your idea of making providers immutable, but it has nothing to do with state

"State" is something that depends on previous calls. These two terms (immutable, stateless) are interdependent/interchangeable in context of services.

> PHP is not using threads...

I made separation "In PHP"/"In general" on purpose.

**Comment by Nyholm** [comment]
How about my questions: 

> What do you think is the best way to proceed? Considering making it easy for people migrating to 4.0? Can you give a example of how all the interfaces should look like, including the new features?

**Comment by unkind** [comment]
Unfortunately, I don't know how to make it easy to migrate, but I can give you my vision of course:
```php
final GeocodingQuery
{
    public static function text(string $query): GeocodingQuery;
    public function withBounds(Bounds $bounds): GeocodingQuery;
    public function withLocale(Locale $locale): GeocodingQuery;
    public function withLimit(int $limit): GeocodingQuery;
}

final ReverseQuery
{
    public static function point(GeoPoint $point): ReverseQuery;
    public function withLimit(int $limit): ReverseQuery;
}

interface Geocoder
{
    public function geocode(GeocodingQuery $query): AddressCollection;
    public function reverse(ReverseQuery $query): AddressCollection;
}

$this->geocoder->geocode(
    GeocodingQuery::text('New York')
        ->withBounds(...)
        ->withLimit(1)
);

$this->geocoder->reverse(
    ReverseQuery::point(...)->withLimit(42)
);
```

**Comment by Nyholm** [comment]
Thank you. I appreciate this concrete suggestion. 👍 

What do you think by adjusting it a little bit like: 

```php
interface Provider // not Geocoder
{
    // Calling it *Query to keep BC
    public function geocodeQuery(GeocodingQuery $query): AddressCollection;
    public function reverseQuery(ReverseQuery $query): AddressCollection;
}

interface Geocoder extends Provider
{
    public function geocode(string $query): AddressCollection;
    public function reverse(string $query): AddressCollection;
    public function getLimit(): int
}
```

This would make it easier to migrate. And it also makes a difference between the Geocoder and the Provider. Providers should not implement the Geocoder interface as they do today. 

An implementation of a Geocoder may look like: 

```php
class MyGeocoder implements Geocoder {
  public function __construct(Provider $provider, string $locale, string $limit) {
    // ..
  }

  public function geocode(string $query) {
    return $this->provider->geocodeQuery(GeocodingQuery::text('New York')
        ->withLocale($this->locale)
        ->withLimit($this->limit));
  }
}
```

**Comment by unkind** [comment]
Why `Geocoder` extends `Provider`?

**Comment by Nyholm** [comment]
I have an idea that it will be helpful when doing AggregatedGeocoder or ChainProviders.

**Comment by djmattyg007** [comment]
> PHP is not using threads...

One day, we will be using threads for PHP applications: https://github.com/php-pm/php-pm

**Comment by Nyholm** [comment]
Thank you for a good discussion.
